- name: Base installation
  connection: local
  hosts: localhost
  tags: [never, base]
  roles: 
    - role: partitions
    - role: mirrorlist
      tags: mirrorlist
    - role: fstab
      tags: fstab
    - role: pacstrap

- name: System configuration
  connection: local
  hosts: localhost
  tags:
    - config
  roles:
    - role: hostname
    - role: hosts
    - role: locale
    - role: yay
      tags: yay
    - role: reflector
      tags: reflector
    - role: zsh
      tags: zsh
    - role: fonts
      tags: fonts
    - role: dotfiles
      tags: dotfiles
    - role: xorg
      tags: xorg
    - role: bspwm
      tags: bspwm
    - role: packages
      tags: packages
