- name: Base installation
  connection: local
  hosts: localhost
  tags: [never, base]
  roles: 
    - role: timedatectl
      tags: timedatectl
    - role: partitions
      tags: partitions
    - role: mirrorlist
      tags: mirrorlist
    - role: pacstrap
      tags: pacstrap
    - role: fstab
      tags: fstab

- name: System configuration
  connection: local
  hosts: localhost
  tags:
    - config
  roles:
    - role: hostname
      tags: hostname
    - role: hosts
      tags: hosts
    - role: locale
      tags: locale
    - role: user
      tags: user
    - role: nvim
      tags: nvim
    - role: yay
      tags: yay
    - role: reflector
      tags: reflector
    - role: zsh
      tags: zsh
    - role: fonts
      tags: fonts
    - role: xorg
      tags: xorg
    - role: bspwm
      tags: bspwm
    - role: dotfiles
      tags: dotfiles
    - role: ssh
      tags: ssh
    - role: packages
      tags: packages

- name: Post-installation
  connection: local
  hosts: localhost
  tags: [never, post-install]
  roles:
    - role: initramfs
      tags: initramfs
    - role: grub
      tags: grub
