- name: Create boot partition
  parted:
    device: "{{ device }}"
    number: 1
    part_end: 512MiB
    flags: [ boot, esp ]
    label: gpt
    state: present

- name: Create data partition
  parted:
    device: "{{ device }}"
    number: 2
    part_start: 512MiB
    part_end: 480GiB
    state: present

- name: Create swap partition
  parted: 
    device: "{{ device }}"
    number: 3
    part_start: 480GiB
    part_end: 100%
    state: present

- name: Create dos filesystem on {{ device }}1
  filesystem:
    dev: "{{ device }}1"
    fstype: vfat
    opts: -F 32

- name: Create ext4 filesystem on {{ device }}2
  filesystem:
    dev: "{{ device }}2"
    fstype: ext4

- name: Create swapfile on {{ device }}3
  command: mkswap {{ device }}3

- name: Turn swap on
  command: swapon {{ device }}3

- name: Mount {{ device }}2 
  mount:
    path: "{{ chroot }}"
    src: "{{ device }}2"
    state: mounted

- name: Create {{ chroot }}/boot directory
  file:
    path: "{{ chroot }}/boot"
    state: directory
    mode: '0755'

- name: Mount {{ device }}1
  mount: 
    path: "{{ chroot }}/boot"
    src: "{{ device }}1"
    state: mounted
